version: '3.8'

services:
  # MongoDB数据库
  mongodb:
    image: mongo:6.0
    container_name: facebook_ads_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: facebook_ads
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - facebook_ads_network

  # Node.js后端应用
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: facebook_ads_backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/facebook_ads?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - facebook_ads_network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: facebook_ads_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./client/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - facebook_ads_network

  # Redis缓存（可选）
  redis:
    image: redis:7-alpine
    container_name: facebook_ads_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - facebook_ads_network

volumes:
  mongodb_data:
  redis_data:

networks:
  facebook_ads_network:
    driver: bridge